name: ogc-cql2

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]
  release:
    types:
      - created

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4

      - name: Restore
        run: dotnet restore OgcCql2.slnx

      - name: Build
        run: |
          dotnet msbuild /m /bl \
            /p:Configuration="Release" \
            /p:Platform="Any CPU" \
            /p:PreReleaseLabel=${GitVersion_PreReleaseLabel} \
            /p:PreReleaseNumber=${GitVersion_WeightedPreReleaseNumber} \
            /p:Version=${GitVersion_FullSemVer} \
            /p:AssemblyVersion=${GitVersion_AssemblySemVer} \
            /p:InformationalVersion=${GitVersion_InformationalVersion} \
            /p:FileVersion=${GitVersion_AssemblySemFileVer} \
            /p:PackageVersion=${GitVersion_FullSemVer} \
            /p:RepositoryUrl="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" \
            /p:PackageProjectUrl="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            /p:BuildInParallel=true \
            /p:ContinuousIntegrationBuild=true \
            OgcCql2.dist.msbuildproj

      - name: Upload MSBuild Log
        if: ${{ always() }}
        uses: actions/upload-artifact@v5
        with:
          name: msbuild.binlog
          path: msbuild.binlog

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v5
        with:
          name: nuget
          path: dist/nuget

      - name: Package tests
        run: tar czvf tests.tar.gz tests
        working-directory: dist

      - name: Upload tests
        uses: actions/upload-artifact@v5
        with:
          name: tests
          path: dist/tests.tar.gz

  test:
    strategy:
      matrix:
        run:
          - OgcCql2.Tests
        sys:
          - linux-x64
        tfm:
          - net10.0
    name: Test (${{ matrix.run }}:${{ matrix.tfm }}:${{ matrix.sys }})
    needs: build
    runs-on: ${{ fromJSON('{"win-x86":["windows-2022"],"win-x64":["windows-2022"],"linux-x64":["ubuntu-24.04"],"linux-arm64":["ubuntu-24.04-arm"],"osx-x64":["macos-15-intel"],"osx-arm64":["macos-15"]}')[matrix.sys] }}
    steps:
      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Download tests
        uses: actions/download-artifact@v5
        with:
          name: tests

      - name: Restore tests
        run: tar xzvf tests.tar.gz

      - name: Execute tests
        timeout-minutes: 480
        shell: pwsh
        run: |
          $run = "${{ matrix.run }}"
          $tfm = "${{ matrix.tfm }}"
          $sys = "${{ matrix.sys }}"

          $tests = Get-Item ".\tests\$run\$tfm\*.Tests.dll"

          if ($tests)
          {
            Add-Content $env:GITHUB_ENV "`nRET=TestResults--$run--$tfm--$sys"
            dotnet test -f $tfm --no-build --results-directory TestResults --logger trx $tests[0].FullName
          }

      - name: Archive test results
        if: always() && startsWith(env.RET, 'TestResults--')
        run: tar czvf TestResults.tar.gz TestResults

      - name: Upload test results
        if: always() && startsWith(env.RET, 'TestResults--')
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.RET }}
          path: TestResults.tar.gz

  release:
    name: Release
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4

      - name: Download NuGet packages
        uses: actions/download-artifact@v5
        with:
          name: nuget
          path: dist/nuget

      - name: Create GitHub release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          makeLatest: true
          artifacts: dist/nuget/*.nupkg,dist/nuget/*.snupkg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push NuGet (GitHub)
        if: github.event_name != 'pull_request'
        shell: pwsh
        run: dotnet nuget push dist/nuget/*.nupkg --source $env:GITHUB_REPOS --api-key $env:GITHUB_TOKEN --skip-duplicate
        env:
          GITHUB_REPOS: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push NuGet
        if: github.ref_type == 'tag'
        shell: pwsh
        run: dotnet nuget push dist/nuget/*.nupkg --source $env:NUGET_REPOS --api-key $env:NUGET_TOKEN --skip-duplicate
        env:
          NUGET_REPOS: https://api.nuget.org/v3/index.json
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
